### ISSUE TITLE
inject failure

### ISSUE THREAD

**Issue by whyseu** [elfmaster/dt_infect#3]
I use the inject tool, but fail to inject the test file. 
![微信图片_20201018104547](https://user-images.githubusercontent.com/35478590/96357510-89533980-112f-11eb-9158-b98a6d38ef58.jpg)

**Comment by elfmaster** [comment]
After you inject it, run 'cp libevil.so /lib/x86_64-linux-gnu/; ldconfig'

This way the dynamic linker can find the shared library. :)

**Comment by whyseu** [comment]
Thank you! But I inject the test file, it does not change the output.
![Uploading 无标题.png…]()

**Comment by whyseu** [comment]
Thank you! But I inject the test file, it does not change the output.
![无标题](https://user-images.githubusercontent.com/35478590/96528504-82eeca00-12b5-11eb-84a7-430967ce76de.png)

**Comment by elfmaster** [comment]
Isn't there a file created called ./keylogger.txt? it should have logged
the input you typed.

-Ryan

**Comment by elfmaster** [comment]
Oh so yeah to clarify, the program you are injecting into is designed to
have liblogger.so injected into it.
You can inject evil.so into something that uses puts() since that's what
its hijacking.

Do ./inject ./liblogger.so <target>; sudo cp liblogger.so <library_path>;
sudo ldconfig;
then run <target> (aka test)

**Comment by whyseu** [comment]
Thank you~
